### ISSUE TITLE
Issues with repost and image post

### ISSUE THREAD

**Issue by ggolcher** [AKASHAorg/akasha-world-framework#1379]
**Describe the bug**
Post with repost and image is misaligned and misspaced. The emojis don't work when I try to put one in. When posted, image is not full width.

**To Reproduce**
Repost a post and add an image

**Expected behavior**
The items should be next to each other, without the spacing in between

**Device**
macOS 12.6, Chrome 94, MetaMask

**Screenshots**
![Screen Shot 2021-10-11 at 1 23 39 PM](https://user-images.githubusercontent.com/15471332/136843415-c8e188b5-6175-452e-98c0-f688b32fb674.png)
![Screen Shot 2021-10-11 at 1 23 53 PM](https://user-images.githubusercontent.com/15471332/136843416-75d3f169-5ca9-4884-8ef8-420ee29b4169.png)
![Screen Shot 2021-10-11 at 1 24 10 PM](https://user-images.githubusercontent.com/15471332/136843417-9987f8df-8b7a-40c2-95a5-f6525aa84208.png)
![Screen Shot 2021-10-11 at 1 24 31 PM](https://user-images.githubusercontent.com/15471332/136843418-988d046e-e380-4f1f-af37-b36c20ba36af.png)

**Comment by ggolcher** [comment]
Inputting emojis still doesn't work
![Screen Shot 2021-10-18 at 1 52 50 PM](https://user-images.githubusercontent.com/15471332/137789880-520b2995-77d8-4a4f-994d-c584dd9e07bc.png)

**Comment by quininez** [comment]
Not being able to add an emoji after an image is a known issue, it is related to slate, the library used for the editor. So far I haven't been able to find a working fix for this. I would close this issue since it contains multiple issues in one, and add this in a separate enhancement issue. What I can provide is a way to add text after an image. Would this behaviour be better than what we have now, or should images always stay as the last element in a post?

**Comment by ggolcher** [comment]
Let's keep them as the last element to make customization with integrations easier, plus more consistent with how posts are made in other social networks.

**Comment by quininez** [comment]
Ok, then I will close this and open a separate issue with the emojis to have it on the backlog
